# GH actions.
name: Conda-CPU-Nightly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '20 6 * * *' # 6:20 AM UTC

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-2016, macOS-latest, ubuntu-latest]
        pkg: ['tlcpack', 'tlcpack-nightly']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda/build-environment.yaml') }}
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: tlcpack-build
        channel-priority: strict
        environment-file: conda/build-environment.yaml
        auto-activate-base: false
        use-only-tar-bz2: true
    - name: Conda info
      run: |
        conda info
        conda list
    - name: TVM checkout
      run: |
        git clone https://github.com/apache/incubator-tvm tvm --recursive
    - name: Sync Package
      run: python common/sync_package.py ${{ matrix.pkg }}
    - name: Conda-Build@Win
      if: startsWith(matrix.os, 'windows')
      shell: cmd /C call {0}
      run: >-
        conda build --output-folder=conda/pkg -m conda/build_config.yaml conda/recipe
    - name: Conda-Build@MacOS
      if: startsWith(matrix.os, 'macOS')
      shell: bash -l {0}
      run: >-
        conda build --output-folder=conda/pkg -m conda/build_config.yaml conda/recipe
    - name: Conda-Build@Linux
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: >-
        conda build --output-folder=conda/pkg -m conda/build_config.yaml conda/recipe
    - name: Conda-Deploy@Win
      if: startsWith(matrix.os, 'windows') && github.ref == 'refs/heads/main'
      shell: cmd /C call {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: >-
        anaconda upload --force --label main conda/pkg/win-64/*.tar.bz2
    - name: Conda-Deploy@MacOS
      if: startsWith(matrix.os, 'macOS') && github.ref == 'refs/heads/main'
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: >-
        anaconda upload --force --label main conda/pkg/osx-64/*.tar.bz2
    - name: Conda-Deploy@Linux
      if: startsWith(matrix.os, 'ubuntu') && github.ref == 'refs/heads/main'
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: >-
        anaconda upload --force --label main conda/pkg/linux-64/*.tar.bz2
